import { CfnOutput, Duration, RemovalPolicy, Stack, type StackProps } from 'aws-cdk-lib';
import {
  InstanceClass,
  InstanceSize,
  InstanceType,
  type IVpc,
  Peer,
  Port,
  SecurityGroup,
  SubnetType,
} from 'aws-cdk-lib/aws-ec2';
import {
  Credentials,
  DatabaseInstance,
  DatabaseInstanceEngine,
  PostgresEngineVersion,
} from 'aws-cdk-lib/aws-rds';
import { type ISecret } from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

export interface DatabaseStackProps extends StackProps {
  /** VPC created by the app orchestrator stack */
  readonly vpc: IVpc;
}

export class DatabaseStack extends Stack {
  /** The RDS PostgreSQL instance (concrete class — exposes .secret) */
  public readonly dbInstance: DatabaseInstance;

  /** The auto-generated secret for hookmate_admin */
  public readonly dbSecret!: ISecret;

  /** Security group allowing inbound PostgreSQL from private subnets */
  public readonly dbSecurityGroup: SecurityGroup;

  constructor(scope: Construct, id: string, props: DatabaseStackProps) {
    super(scope, id, props);

    const { vpc } = props;

    // --- Security Group ---
    // Only allow PostgreSQL traffic (5432) from within the VPC's private subnets.
    // Lambda functions and other internal services in private subnets can reach the DB.
    this.dbSecurityGroup = new SecurityGroup(this, 'DatabaseSecurityGroup', {
      vpc,
      description: 'Allow PostgreSQL access from private subnets only',
      allowAllOutbound: false,
    });

    this.dbSecurityGroup.addIngressRule(
      Peer.ipv4(vpc.vpcCidrBlock),
      Port.tcp(5432),
      'Allow PostgreSQL from VPC private subnets',
    );

    // --- RDS PostgreSQL Instance ---
    // t3.micro, single-AZ (cost constraint), 20GB storage with autoscaling to 100GB.
    // Credentials are auto-generated by CDK and stored in Secrets Manager.
    this.dbInstance = new DatabaseInstance(this, 'HookMateDB', {
      engine: DatabaseInstanceEngine.postgres({
        version: PostgresEngineVersion.VER_16,
      }),
      instanceType: InstanceType.of(InstanceClass.T3, InstanceSize.MICRO),
      vpc,
      vpcSubnets: { subnetType: SubnetType.PRIVATE_WITH_EGRESS },
      multiAz: false, // cost constraint for portfolio — set true for production
      allocatedStorage: 20,
      maxAllocatedStorage: 100,
      deletionProtection: false, // set true for production
      removalPolicy: RemovalPolicy.DESTROY, // safe for dev/portfolio — change for prod
      databaseName: 'hookmate',
      credentials: Credentials.fromGeneratedSecret('hookmate_admin'),
      storageEncrypted: true, // encryption at rest with AWS-managed KMS key
      backupRetention: Duration.days(7),
      monitoringInterval: Duration.seconds(60),
      enablePerformanceInsights: true,
    });

    // Assign the auto-generated secret (CDK always creates one with fromGeneratedSecret)
    this.dbSecret = this.dbInstance.secret!;

    // --- Outputs ---
    new CfnOutput(this, 'DbEndpoint', {
      value: this.dbInstance.dbInstanceEndpointAddress,
      description: 'RDS PostgreSQL endpoint address',
    });

    new CfnOutput(this, 'DbPort', {
      value: this.dbInstance.dbInstanceEndpointPort,
      description: 'RDS PostgreSQL port',
    });

    new CfnOutput(this, 'DbSecretArn', {
      value: this.dbSecret.secretArn,
      description: 'Secrets Manager ARN for DB credentials',
    });
  }
}
